CREATE TABLE IF NOT EXISTS CATEGORY(
     CATEGORY_ID LONG NOT NULL AUTO_INCREMENT,
     CATEGORY_ICON CHAR(20) DEFAULT 'Loading' NOT NULL,
     CATEGORY_COLOR CHAR(20) DEFAULT 'red' NOT NULL,
     CATEGORY_THEME CHAR(20) DEFAULT 'Sample' NOT NULL,
     TENANT_ID CHAR(20) NOT NULL,
     PRIMARY KEY (CATEGORY_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ITEM(
     ITEM_ID INT NOT NULL AUTO_INCREMENT,
     CATEGORY_ID LONG NOT NULL,
     ITEM_NAME CHAR(20) DEFAULT '' NOT NULL,
     ITEM_VALUE CHAR(20) DEFAULT '' NOT NULL,
     PRIMARY KEY (ITEM_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;