server:
  port: 8083
  servlet:
    context-path: /onenote
spring:
  profiles:
    active: prod
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # 自动创建表以及更新表结构，生产环境慎用
    show-sql: true # 打印执行的SQL
